In [4]:
import numpy as np
from datetime import datetime, date, time
import pandas as pd

In [3]:
#SINGLE VALUE IN PYTHON LIST
l = [10,1]
1 in l

True

In [ ]:
#WHOLE PANDAS COLUMN IN PYTHON LIST
s['ColumnName'].isin(listname).all()

In [ ]:
#PANDAS ROWS BY CONDITION IN OTHER PANDAS ROWS

caricati[caricati['NodeId']==VALORE] #standard approach

#condition tested in another df
caricati[caricati['NodeId'].isin(sub_df['ToNodeId'].values)]['msgIdTangle'].values[0] 

In [4]:
#PRINT LAST X VALUES
df.tail(X)

NameError: name 'df' is not defined

In [ ]:
#RESET INDEX TO DF
s.reset_index(drop = True, inplace = True)

In [8]:
#ADD DINAMICALLY ROWS TO DF AND ACCESS TO THEM
caricati = pd.DataFrame(columns=['NodeId','msgIdTangle']) #definisco df

last = len(caricati)

caricati.loc[last,'NodeId'] = 'a' #aggiungo valori
caricati.loc[last,'msgIdTangle'] = 'valore'

last = len(caricati)

caricati.loc[last,'NodeId'] = 'a' #aggiungo valori
caricati.loc[last,'msgIdTangle'] = 'valore'

last = len(caricati)

caricati.loc[last,'NodeId'] = 'b' #aggiungo valori
caricati.loc[last,'msgIdTangle'] = 'valore2'


caricati

NodeId msgIdTangle
0      a      valore
1      a      valore
2      b     valore2

In [14]:
#GET UNIQUE VALUES FROM DATAFRAME COLUMN
q = caricati[caricati['NodeId']=='a']['NodeId']
np.unique(q.values)[0]

'a'

In [5]:
#SCAN VALUES IN LIST
ll = ['a','b']
for i in ll:
    print(i)

a
b


In [18]:
#REMOVE ELEMENT FROM LIST
ll.remove('a')
ll

['b']

In [21]:
#NUMPY UNIQUE AND DELETE
res = np.unique([1,2,4,3,2,1,4,2,4])
print(res)
res = np.delete(res, np.argwhere(res == 1))
print(res)

[1 2 3 4]
[2 3 4]


In [46]:
#USO CLASSICO DI DB SU PANDAS

database = pd.DataFrame(columns=['Autore1','Autore2']) #definisco df



database.loc['Autore1','Autore1'] = 'si' #aggiungo valori
database.loc['Autore1','Autore2'] = 'no'

database.loc['Autore2','Autore1'] = 'si' #aggiungo valori
database.loc['Autore2','Autore2'] = 'no'

database.loc['Autore3','Autore1'] = 'no' #aggiungo valori
database.loc['Autore3','Autore2'] = 'no'

database.loc['Autore4','Autore1'] = 'nn' #aggiungo valori
database.loc['Autore4','Autore2'] = 'nn'

database

Autore1 Autore2
Autore1      si      no
Autore2      si      no
Autore3      no      no
Autore4      nn      nn

In [47]:
#NUMPY UNIQUE VALUE COUNT
res = np.unique(database.Autore1.values,return_counts=True)
res

(array(['nn', 'no', 'si'], dtype=object), array([1, 1, 2], dtype=int64))

In [49]:
#NUMPY ACCESS TO UNIQUE VALUES COUNT
for i in range(len(res[0])):
    print(res[0][i])
    print(res[1][i])
    print('')

nn
1

no
1

si
2



In [51]:
#df to txt

database = pd.DataFrame(columns=['Autore1','Autore2']) #definisco df



database.loc['Autore1','Autore1'] = 'si' #aggiungo valori
database.loc['Autore1','Autore2'] = 'no'

np.savetxt(r'./valori.txt', database.values, fmt='%s')

In [ ]:
#LAST X ROWS OF DF
df.tail(X)

In [65]:
#NOT IN
caricati1 = pd.DataFrame(columns=['NodeId','msgIdTangle']) #definisco df

last = len(caricati1)

caricati1.loc[last,'NodeId'] = 'a' #aggiungo valori
caricati1.loc[last,'msgIdTangle'] = 'valore'

last = len(caricati1)

caricati1.loc[last,'NodeId'] = 'b' #aggiungo valori
caricati1.loc[last,'msgIdTangle'] = 'valore2'

print(caricati1)

print('a' not in caricati1['NodeId'].values)
print('c' not in caricati1['NodeId'].values)



  NodeId msgIdTangle
0      a      valore
1      b     valore2
False
True


In [70]:
#REVERSE FOR 
for i in range(len(caricati1)-1,-1,-1):
    print(i)

1
0


In [ ]:
#READ NUMPY TXT FILE
AM_matrix = np.loadtxt('./AM_Matrix.txt')

In [ ]:
#RENAME A COLUMN
DF.rename(columns={'old':'new'}, inplace = True)

In [71]:
#EASY WAY TO DEF NP MATRIX
Mat = np.matrix('0 1 2; 2 0 3 ; 1 1 0')
Mat

matrix([[0, 1, 2],
        [2, 0, 3],
        [1, 1, 0]])

In [ ]:
#DF QUERY ON VALUES
df.query('attribute == attribute.max()')

In [80]:
#ASSIGN AND CHECK NaN VALUE
import math
a = float("NaN")
math.isnan(a)

True

In [1]:
#TIME ESTIMATION
from timeit import default_timer as timer
start = timer()
end = timer()
print(end - start)

4.859999990003416e-05


In [ ]:
#STRING SPLIT BY CHAR
splitted = da_splittare.split("\n ")
splitted

In [2]:
#STRING CONTAINS
'-' in stringa

NameError: name 'stringa' is not defined

In [ ]:
#ADD NEW COLUMN TO DF
E_matrix['NUOVA_COLONNA'] = new_values

In [ ]:
#DROP ROW FROM DF IF USING LOC ON ENTRY
E_matrix.drop(index = 'LOC ENTRY', inplace=True)

In [ ]:
#DROP COLUMN FROM DF 
E_matrix = E_matrix.drop(['COLNAME1', 'COLNAME2'], axis=1)

In [ ]:
#PLOT ZOOM 
plt.axis([x_min, x_max, y_min, y_max])

In [ ]:
#BOX PLOT
plt.boxplot(DB_AA.groupby(by='To_Author_Seed')['ToNodeId'].count().values)

In [ ]:
#TILDE
~

In [ ]:
#PLOT MULTIPLE LINES
plt.plot(x, y, label = "line 1")
plt.plot(y, x, label = "line 2")
plt.legend()
plt.show()

In [ ]:
#SET LABELS ON AXIS
plt.xlabel('COMMUNITY')
plt.ylabel('CITAZIONI')

In [2]:
#COSINE SIMILARITY ONLY COMPUTING THE DISTANCE BETWEEN SYNTAX (POSITION AND OCCOURENCES OF WORDS)
from strsimpy.cosine import Cosine

cosine = Cosine(2)
s0 = 'My sequence'
s1 = 'My string'
p0 = cosine.get_profile(s0)
p1 = cosine.get_profile(s1)
print(cosine.similarity_profiles(p0, p1))

0.33541019662496846


In [3]:
#COSINE SIMILARITY COMPUTING THE DISTANCE BETWEEN SEMANTIC (POSITION AND OCCOURENCES OF WORDS EXPLOTING A CORPUS AND AI)

import pandas as pd
import numpy as np
import string
import itertools
import spacy

# function to remove punctuation from text (input is a string)
def clean_text(sentence):
    
    clean_sentence = "".join(l for l in sentence if l not in string.punctuation)
    
    return clean_sentence

# function to calculate the cosine
def cosine_similarity_calc(vec_1,vec_2):
    
    sim = np.dot(vec_1,vec_2)/(np.linalg.norm(vec_1)*np.linalg.norm(vec_2))
    
    return sim

# function to calculate cosine similarity using word vectors (input is a series)
def embeddings_similarity(sentences):
    
    # first we need to get data into | sentence_a | sentence_b | format
    sentence_pairs = list(itertools.combinations(sentences, 2))
    
    sentence_a = [pair[0] for pair in sentence_pairs]
    sentence_b = [pair[1] for pair in sentence_pairs]
    
    sentence_pairs_df = pd.DataFrame({'sentence_a':sentence_a, 'sentence_b':sentence_b})
    
    # get unique combinations of sentance_a and sentance_b
    sentence_pairs_df = sentence_pairs_df.loc[
        pd.DataFrame(
            np.sort(sentence_pairs_df[['sentence_a', 'sentence_b']],1),
            index=sentence_pairs_df.index
        ).drop_duplicates(keep='first').index
    ]

    # remove instances where sentence a == sentence b
    sentence_pairs_df = sentence_pairs_df[sentence_pairs_df['sentence_a'] != sentence_pairs_df['sentence_b']]
    
    # load word embeddings (will use these to convert sentence to vectors)
    # Note you will need to run the following command (from cmd) to download embeddings: 
    # 'python -m spacy download en_core_web_lg'
    embeddings = spacy.load('en_core_web_lg')
    
    # now we are ready to calculate the similarity
    
    sentence_pairs_df['similarity'] = sentence_pairs_df.apply(
        lambda row: cosine_similarity_calc(
            embeddings(clean_text(row['sentence_a'])).vector, 
            embeddings(clean_text(row['sentence_b'])).vector), 
        axis=1
    )
    
    return sentence_pairs_df


#NB: 
#−1 value will indicate strongly opposite vectors

#0 independent (orthogonal) vectors

#1 similar (positive co-linear) vectors. Intermediate values are used to assess the degree of similarity.


# calculate similarity for sample sentences
sentences = ['My string', 'My sequence']
print(embeddings_similarity(sentences))

  sentence_a   sentence_b  similarity
0  My string  My sequence    0.947855


In [ ]:
#STRING TO BYTE & REVERSE
my_str = "hello world"
my_str_as_bytes = str.encode(my_str)
print(my_str_as_bytes)
print(type(my_str_as_bytes)) # ensure it is byte representation
my_decoded_str = my_str_as_bytes.decode()
print(my_decoded_str)
print(type(my_decoded_str))

In [15]:
#LAMBDA FUN

#index => axis=0
#columns => axis = 1
database = pd.DataFrame(columns=['A','B']) #definisco df



database.loc['1','A'] = 'si' #aggiungo valori
database.loc['2','A'] = 'no'

database.loc['1','B'] = 'boh' #aggiungo valori
database.loc['2','B'] = 'forse'

print(database)

database['A'] = database['B'].apply(lambda row : row+'K')

database

    A      B
1  si    boh
2  no  forse


A      B
1    bohK    boh
2  forseK  forse